name: aspnetlogging
version: 1.0.0
summary: dummy for deletion
description: dummy for deletion
runner: ARM
templatePath: main.bicep
parameters:
- id: "region"
  name: "region"
  description: "region for main resources"
  type: "string"
  required: true
